[package]
name = "libbare"
version = "0.0.0"
edition = "2018"
authors = ["ㄗㄠˋ ㄑㄧˊ <tsao-chi@the-lingo.org>"]
repository = "https://github.com/Otcoy/libbare"
description = "libbare: statically linkable and dynamically loadable drivers"
license = "MPL-2.0"
categories = [ "no-std" ]

[profile.dev]
panic = "abort"

[dependencies]
no-std-compat = { version = "0.4.1", features = [ "alloc" ] }
lazy_static = "1.4.0"
spin = "0.9.0"
x86_64 = { version = "0.14.3", optional = true }

[features]
default = []
#default = [ "std" ] # Default to using the std
std = [ "no-std-compat/std" ]